apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ictu-toestemmingen
namePrefix: toestemmingen-

resources:
  - ../../base

images:
  - name: frontend-image
    newName: nginx
    newTag: mainline
patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: ictu-toestemmingen.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ictu-toestemmingen.apps.digilab.network
